// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh4TZKz7WA3-dfZYmiDpeqXX4HB11JvMc',
    appId: '1:610812706144:web:1ff3d0c612a6a05c957205',
    messagingSenderId: '610812706144',
    projectId: 'tabbller-8a6ef',
    authDomain: 'tabbller-8a6ef.firebaseapp.com',
    storageBucket: 'tabbller-8a6ef.firebasestorage.app',
    measurementId: 'G-Y39Q2FR3C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI40kQ0ZzH9ebdRaub9fP8c8IZhgNgW_I',
    appId: '1:610812706144:android:c781a8de8c59e4ac957205',
    messagingSenderId: '610812706144',
    projectId: 'tabbller-8a6ef',
    storageBucket: 'tabbller-8a6ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfSsNhzG1pQM2ZRKzzV-UdYpxe-yvxf1A',
    appId: '1:610812706144:ios:8d9a3b868b1e5352957205',
    messagingSenderId: '610812706144',
    projectId: 'tabbller-8a6ef',
    storageBucket: 'tabbller-8a6ef.firebasestorage.app',
    iosClientId: '610812706144-qgemo9ndjg5c9opogcb76sau8mudj5ji.apps.googleusercontent.com',
    iosBundleId: 'com.pxlbytstudio.tabbller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfSsNhzG1pQM2ZRKzzV-UdYpxe-yvxf1A',
    appId: '1:610812706144:ios:839e2a64534b5fc3957205',
    messagingSenderId: '610812706144',
    projectId: 'tabbller-8a6ef',
    storageBucket: 'tabbller-8a6ef.firebasestorage.app',
    iosClientId: '610812706144-lrmu3k3kkanoc0smk0a0vdap83th2107.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabbller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh4TZKz7WA3-dfZYmiDpeqXX4HB11JvMc',
    appId: '1:610812706144:web:2e4795265901a4fa957205',
    messagingSenderId: '610812706144',
    projectId: 'tabbller-8a6ef',
    authDomain: 'tabbller-8a6ef.firebaseapp.com',
    storageBucket: 'tabbller-8a6ef.firebasestorage.app',
    measurementId: 'G-BMD6N9569M',
  );

}